server:
  port: ${port:8084}

app:
  services:
    - { id: DashboardService, host: "http://localhost:8082/metrics" }
    - { id: MicroServiceDashboard, host: "http://localhost:8084/metrics" }
  async:
    name: ActuatorExecutor
    corePoolSize: 7
    maxPoolSize: 20
    queueCapacity: 20

logging:
  level:
    io:
      dashboardhub:
        dashboard:
          microservice: DEBUG

---
spring:
  profiles: prod
server:
  port: ${port:80}
